baseURL = 'https://fireteam.christmas/'
languageCode = 'en-us'
title = 'fireteam christmas'
theme = 'sleigher'
assetDir = 'static'
[menu]
	[[menu.main]]
		name = 'posts'
#		pageRef = '/other'
		weight = 1
	[[menu.main]]
		name = 'recipes'
#		pageRef = '/recipes'
		weight = 2
	[[menu.main]]
		name = 'transcriptions'
#		pageRef = '/transcriptions'
		weight = 3
	[[menu.extra]]
		name = 'cool links'
		pageRef = '/links'
		url = '/links'
		weight = 4
